from os import path

import numpy as np
from rdkit import Chem
from rdkit.Chem import QED
from rdkit.Chem.Draw import MolsToGridImage

# list generated by a model
smiles_list = [
    'CCCCCCNNNNNCCOCCCCCCCCNNNNNCCOCC'
]

molecules = [Chem.MolFromSmiles(x) for x in smiles_list]

print(sorted([x.GetNumAtoms() for x in molecules]))

good_mol_list = [x for x in molecules if 10 < x.GetNumAtoms() < 50]
print(len(good_mol_list))

qed_list = [QED.qed(x) for x in good_mol_list]
# final_mol_list = [(a,b) for a,b in zip(good_mol_list, qed_list) if b > 0.1]
final_mol_list = [(a,b) for a,b in zip(good_mol_list, qed_list)]

print('Final list %s', final_mol_list)

svg = MolsToGridImage([x[0] for x in final_mol_list],
    molsPerRow=3,
    useSVG=True,
    subImgSize=(250,250),
    legends=[f"{x[1]:.2f}" for x in final_mol_list]
)

filename = 'mols.svg'
with open(filename, 'w') as f:
    f.write(svg)
print(filename)

fullpath = path.join(path.dirname(path.realpath(__file__)), filename)
print(fullpath)